apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudflared
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: ''
    namespace: cloudflared
    server: 'https://kubernetes.default.svc'
  source:
    path: kubernetes/apps/networking/cloudflared
    repoURL: 'git@github.com:AnthonyStainer/homeops.git'
    targetRevision: HEAD
    directory:
      recurse: true
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
