apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jellyfin
spec:
  destination:
    name: ''
    namespace: jellyfin
    server: 'https://kubernetes.default.svc'
  source:
    path: kubernetes/apps/media/jellyfin
    repoURL: 'git@github.com:AnthonyStainer/homeops.git'
    targetRevision: HEAD
    directory:
      recurse: true
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true