apiVersion: apps/v1
kind: Deployment
metadata:
  name: qbittorrent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qbittorrent
  template:
    metadata:
      labels:
        app: qbittorrent
    spec:
      containers:
      - name: qbittorrent
        image: linuxserver/qbittorrent:4.6.3-r0-ls315
        ports:
        - containerPort: 8080
          name: webui
        - containerPort: 6881
          name: bt
          protocol: UDP
        env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: TZ
          value: "Europe/London"
        - name: UMASK_SET
          value: "022"
        - name: WEBUI_PORT
          value: "8080"
        volumeMounts:
        - name: qbittorrent-config
          mountPath: /config
        - name: media
          mountPath: /media
      volumes:
      - name: qbittorrent-config
        persistentVolumeClaim:
          claimName: qbittorrent-config-pvc
      - name: media
        persistentVolumeClaim:
          claimName: media-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: qbittorrent
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: webui
  - port: 6881
    targetPort: 6881
    protocol: UDP
    name: bt
  selector:
    app: qbittorrent