apiVersion: apps/v1
kind: Deployment
metadata:
  name: radarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: radarr
  template:
    metadata:
      labels:
        app: radarr
    spec:
      containers:
      - name: radarr
        image: linuxserver/radarr:version-5.3.6.8612
        ports:
        - containerPort: 7878
        volumeMounts:
        - mountPath: "/config"
          name: radarr-config
      volumes:
      - name: radarr-config
        persistentVolumeClaim:
          claimName: radarr-config-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: radarr
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 7878
    protocol: TCP
  selector:
    app: radarr
